[2024-09-19T09:29:46.396+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T09:29:46.403+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitoring_dag.data_drift_detected manual__2024-09-19T09:29:40.655795+00:00 [queued]>
[2024-09-19T09:29:46.406+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitoring_dag.data_drift_detected manual__2024-09-19T09:29:40.655795+00:00 [queued]>
[2024-09-19T09:29:46.406+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-19T09:29:46.410+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): data_drift_detected> on 2024-09-19 09:29:40.655795+00:00
[2024-09-19T09:29:46.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=449) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-19T09:29:46.414+0000] {standard_task_runner.py:72} INFO - Started process 464 to run task
[2024-09-19T09:29:46.415+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'monitoring_dag', 'data_drift_detected', 'manual__2024-09-19T09:29:40.655795+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmpxfdsojlj']
[2024-09-19T09:29:46.416+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask data_drift_detected
[2024-09-19T09:29:46.432+0000] {task_command.py:467} INFO - Running <TaskInstance: monitoring_dag.data_drift_detected manual__2024-09-19T09:29:40.655795+00:00 [running]> on host d2d815eb1dcc
[2024-09-19T09:29:46.460+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitoring_dag' AIRFLOW_CTX_TASK_ID='data_drift_detected' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T09:29:40.655795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T09:29:40.655795+00:00'
[2024-09-19T09:29:46.460+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T09:29:47.531+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:29:47.532+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:29:47.533+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:29:47.533+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:29:47.731+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:29:47.731+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:29:47.732+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:29:47.733+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:29:50.130+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-19T09:29:50.139+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T09:29:50.140+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=monitoring_dag, task_id=data_drift_detected, run_id=manual__2024-09-19T09:29:40.655795+00:00, execution_date=20240919T092940, start_date=20240919T092946, end_date=20240919T092950
[2024-09-19T09:29:50.179+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T09:29:50.192+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-19T09:29:50.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
