[2024-09-19T09:08:15.054+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T09:08:15.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitoring_dag.detect_data_drift manual__2024-09-19T09:08:11.262247+00:00 [queued]>
[2024-09-19T09:08:15.066+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitoring_dag.detect_data_drift manual__2024-09-19T09:08:11.262247+00:00 [queued]>
[2024-09-19T09:08:15.066+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-19T09:08:15.072+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): detect_data_drift> on 2024-09-19 09:08:11.262247+00:00
[2024-09-19T09:08:15.075+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-19T09:08:15.076+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2024-09-19T09:08:15.076+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'monitoring_dag', 'detect_data_drift', 'manual__2024-09-19T09:08:11.262247+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmpqcq23qu4']
[2024-09-19T09:08:15.077+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask detect_data_drift
[2024-09-19T09:08:15.095+0000] {task_command.py:467} INFO - Running <TaskInstance: monitoring_dag.detect_data_drift manual__2024-09-19T09:08:11.262247+00:00 [running]> on host d2d815eb1dcc
[2024-09-19T09:08:15.121+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitoring_dag' AIRFLOW_CTX_TASK_ID='detect_data_drift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T09:08:11.262247+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T09:08:11.262247+00:00'
[2024-09-19T09:08:15.121+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T09:08:15.126+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-19T09:08:15.148+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:08:15.149+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:08:15.150+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:08:15.150+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:08:15.181+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:08:15.182+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:08:15.182+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-09-19T09:08:15.183+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-09-19T09:08:15.208+0000] {python.py:240} INFO - Done. Returned value was: data_drift_detected
[2024-09-19T09:08:15.208+0000] {branch.py:38} INFO - Branch into data_drift_detected
[2024-09-19T09:08:15.209+0000] {skipmixin.py:230} INFO - Following branch ('data_drift_detected',)
[2024-09-19T09:08:15.213+0000] {skipmixin.py:278} INFO - Skipping tasks [('no_data_drift_detected', -1)]
[2024-09-19T09:08:15.222+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T09:08:15.223+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=monitoring_dag, task_id=detect_data_drift, run_id=manual__2024-09-19T09:08:11.262247+00:00, execution_date=20240919T090811, start_date=20240919T090815, end_date=20240919T090815
[2024-09-19T09:08:15.269+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T09:08:15.281+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-19T09:08:15.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
